from app import app


class Cereals(app.db.Model):
    __tablename__ = 'cereais_e_derivados'

    id = app.db.Column('index', app.db.Integer, primary_key=True)
    description = app.db.Column('Descrição', app.db.String)
    humidity = app.db.Column('Umidade (%)', app.db.Float)
    energy_kcal = app.db.Column('Energia (kcal)', app.db.Integer)
    energy_kj = app.db.Column('Energia (kJ)', app.db.Integer)
    protein = app.db.Column('Proteína (g)', app.db.Float)
    fat = app.db.Column('Lipídeos (g)', app.db.Float)
    cholesterol = app.db.Column('Colesterol (mg)', app.db.Float)
    carbs = app.db.Column('Carboidrato (g)', app.db.Float)
    fiber = app.db.Column('Fibra Alimentar (g)', app.db.Float)
    calcium = app.db.Column('Cálcio (mg)', app.db.Float)
    magnesium = app.db.Column('Magnésio (mg)', app.db.Float)
    manganese = app.db.Column('Manganés (mg)', app.db.Float)
    phosphorus = app.db.Column('Fósforo (mg)', app.db.Float)
    iron = app.db.Column('Ferro (mg)', app.db.Float)
    sodium = app.db.Column('Sódio (mg)', app.db.Float)
    potassium = app.db.Column('Potássio (mg)', app.db.Float)
    copper = app.db.Column('Cobre (mg)', app.db.Float)
    zinc = app.db.Column('Zinco (mg)', app.db.Float)
    retinol = app.db.Column('Retinol (mcg)', app.db.Float)
    thiamine = app.db.Column('Tiamina (mg)', app.db.Float)
    riboflavin = app.db.Column('Riboflavina (mg)', app.db.Float)
    pyridoxine = app.db.Column('Piridoxina (mg)', app.db.Float)
    niacin = app.db.Column('Niacina (mg)', app.db.Float)
    vitamin_c = app.db.Column('Vitamina C (mg)', app.db.Float)


class Vegetables(app.db.Model):
    __tablename__ = 'verduras_hortalicas_e_derivados'

    id = app.db.Column('index', app.db.Integer, primary_key=True)
    description = app.db.Column('Descrição', app.db.String)
    humidity = app.db.Column('Umidade (%)', app.db.Float)
    energy_kcal = app.db.Column('Energia (kcal)', app.db.Integer)
    energy_kj = app.db.Column('Energia (kJ)', app.db.Integer)
    protein = app.db.Column('Proteína (g)', app.db.Float)
    fat = app.db.Column('Lipídeos (g)', app.db.Float)
    cholesterol = app.db.Column('Colesterol (mg)', app.db.Float)
    carbs = app.db.Column('Carboidrato (g)', app.db.Float)
    fiber = app.db.Column('Fibra Alimentar (g)', app.db.Float)
    calcium = app.db.Column('Cálcio (mg)', app.db.Float)
    magnesium = app.db.Column('Magnésio (mg)', app.db.Float)
    manganese = app.db.Column('Manganés (mg)', app.db.Float)
    phosphorus = app.db.Column('Fósforo (mg)', app.db.Float)
    iron = app.db.Column('Ferro (mg)', app.db.Float)
    sodium = app.db.Column('Sódio (mg)', app.db.Float)
    potassium = app.db.Column('Potássio (mg)', app.db.Float)
    copper = app.db.Column('Cobre (mg)', app.db.Float)
    zinc = app.db.Column('Zinco (mg)', app.db.Float)
    retinol = app.db.Column('Retinol (mcg)', app.db.Float)
    thiamine = app.db.Column('Tiamina (mg)', app.db.Float)
    riboflavin = app.db.Column('Riboflavina (mg)', app.db.Float)
    pyridoxine = app.db.Column('Piridoxina (mg)', app.db.Float)
    niacin = app.db.Column('Niacina (mg)', app.db.Float)
    vitamin_c = app.db.Column('Vitamina C (mg)', app.db.Float)


class Fruits(app.db.Model):
    __tablename__ = 'frutas_e_derivados'

    id = app.db.Column('index', app.db.Integer, primary_key=True)
    description = app.db.Column('Descrição', app.db.String)
    humidity = app.db.Column('Umidade (%)', app.db.Float)
    energy_kcal = app.db.Column('Energia (kcal)', app.db.Integer)
    energy_kj = app.db.Column('Energia (kJ)', app.db.Integer)
    protein = app.db.Column('Proteína (g)', app.db.Float)
    fat = app.db.Column('Lipídeos (g)', app.db.Float)
    cholesterol = app.db.Column('Colesterol (mg)', app.db.Float)
    carbs = app.db.Column('Carboidrato (g)', app.db.Float)
    fiber = app.db.Column('Fibra Alimentar (g)', app.db.Float)
    calcium = app.db.Column('Cálcio (mg)', app.db.Float)
    magnesium = app.db.Column('Magnésio (mg)', app.db.Float)
    manganese = app.db.Column('Manganés (mg)', app.db.Float)
    phosphorus = app.db.Column('Fósforo (mg)', app.db.Float)
    iron = app.db.Column('Ferro (mg)', app.db.Float)
    sodium = app.db.Column('Sódio (mg)', app.db.Float)
    potassium = app.db.Column('Potássio (mg)', app.db.Float)
    copper = app.db.Column('Cobre (mg)', app.db.Float)
    zinc = app.db.Column('Zinco (mg)', app.db.Float)
    retinol = app.db.Column('Retinol (mcg)', app.db.Float)
    thiamine = app.db.Column('Tiamina (mg)', app.db.Float)
    riboflavin = app.db.Column('Riboflavina (mg)', app.db.Float)
    pyridoxine = app.db.Column('Piridoxina (mg)', app.db.Float)
    niacin = app.db.Column('Niacina (mg)', app.db.Float)
    vitamin_c = app.db.Column('Vitamina C (mg)', app.db.Float)


class Fats(app.db.Model):
    __tablename__ = 'gorduras_e_oleos'

    id = app.db.Column('index', app.db.Integer, primary_key=True)
    description = app.db.Column('Descrição', app.db.String)
    humidity = app.db.Column('Umidade (%)', app.db.Float)
    energy_kcal = app.db.Column('Energia (kcal)', app.db.Integer)
    energy_kj = app.db.Column('Energia (kJ)', app.db.Integer)
    protein = app.db.Column('Proteína (g)', app.db.Float)
    fat = app.db.Column('Lipídeos (g)', app.db.Float)
    cholesterol = app.db.Column('Colesterol (mg)', app.db.Float)
    carbs = app.db.Column('Carboidrato (g)', app.db.Float)
    fiber = app.db.Column('Fibra Alimentar (g)', app.db.Float)
    calcium = app.db.Column('Cálcio (mg)', app.db.Float)
    magnesium = app.db.Column('Magnésio (mg)', app.db.Float)
    manganese = app.db.Column('Manganés (mg)', app.db.Float)
    phosphorus = app.db.Column('Fósforo (mg)', app.db.Float)
    iron = app.db.Column('Ferro (mg)', app.db.Float)
    sodium = app.db.Column('Sódio (mg)', app.db.Float)
    potassium = app.db.Column('Potássio (mg)', app.db.Float)
    copper = app.db.Column('Cobre (mg)', app.db.Float)
    zinc = app.db.Column('Zinco (mg)', app.db.Float)
    retinol = app.db.Column('Retinol (mcg)', app.db.Float)
    thiamine = app.db.Column('Tiamina (mg)', app.db.Float)
    riboflavin = app.db.Column('Riboflavina (mg)', app.db.Float)
    pyridoxine = app.db.Column('Piridoxina (mg)', app.db.Float)
    niacin = app.db.Column('Niacina (mg)', app.db.Float)
    vitamin_c = app.db.Column('Vitamina C (mg)', app.db.Float)


class Seafood(app.db.Model):
    __tablename__ = 'pescados_e_frutos_do_mar'

    id = app.db.Column('index', app.db.Integer, primary_key=True)
    description = app.db.Column('Descrição', app.db.String)
    humidity = app.db.Column('Umidade (%)', app.db.Float)
    energy_kcal = app.db.Column('Energia (kcal)', app.db.Integer)
    energy_kj = app.db.Column('Energia (kJ)', app.db.Integer)
    protein = app.db.Column('Proteína (g)', app.db.Float)
    fat = app.db.Column('Lipídeos (g)', app.db.Float)
    cholesterol = app.db.Column('Colesterol (mg)', app.db.Float)
    carbs = app.db.Column('Carboidrato (g)', app.db.Float)
    fiber = app.db.Column('Fibra Alimentar (g)', app.db.Float)
    calcium = app.db.Column('Cálcio (mg)', app.db.Float)
    magnesium = app.db.Column('Magnésio (mg)', app.db.Float)
    manganese = app.db.Column('Manganés (mg)', app.db.Float)
    phosphorus = app.db.Column('Fósforo (mg)', app.db.Float)
    iron = app.db.Column('Ferro (mg)', app.db.Float)
    sodium = app.db.Column('Sódio (mg)', app.db.Float)
    potassium = app.db.Column('Potássio (mg)', app.db.Float)
    copper = app.db.Column('Cobre (mg)', app.db.Float)
    zinc = app.db.Column('Zinco (mg)', app.db.Float)
    retinol = app.db.Column('Retinol (mcg)', app.db.Float)
    thiamine = app.db.Column('Tiamina (mg)', app.db.Float)
    riboflavin = app.db.Column('Riboflavina (mg)', app.db.Float)
    pyridoxine = app.db.Column('Piridoxina (mg)', app.db.Float)
    niacin = app.db.Column('Niacina (mg)', app.db.Float)
    vitamin_c = app.db.Column('Vitamina C (mg)', app.db.Float)


class Meet(app.db.Model):
    __tablename__ = 'carnes_e_derivados'

    id = app.db.Column('index', app.db.Integer, primary_key=True)
    description = app.db.Column('Descrição', app.db.String)
    humidity = app.db.Column('Umidade (%)', app.db.Float)
    energy_kcal = app.db.Column('Energia (kcal)', app.db.Integer)
    energy_kj = app.db.Column('Energia (kJ)', app.db.Integer)
    protein = app.db.Column('Proteína (g)', app.db.Float)
    fat = app.db.Column('Lipídeos (g)', app.db.Float)
    cholesterol = app.db.Column('Colesterol (mg)', app.db.Float)
    carbs = app.db.Column('Carboidrato (g)', app.db.Float)
    fiber = app.db.Column('Fibra Alimentar (g)', app.db.Float)
    calcium = app.db.Column('Cálcio (mg)', app.db.Float)
    magnesium = app.db.Column('Magnésio (mg)', app.db.Float)
    manganese = app.db.Column('Manganés (mg)', app.db.Float)
    phosphorus = app.db.Column('Fósforo (mg)', app.db.Float)
    iron = app.db.Column('Ferro (mg)', app.db.Float)
    sodium = app.db.Column('Sódio (mg)', app.db.Float)
    potassium = app.db.Column('Potássio (mg)', app.db.Float)
    copper = app.db.Column('Cobre (mg)', app.db.Float)
    zinc = app.db.Column('Zinco (mg)', app.db.Float)
    retinol = app.db.Column('Retinol (mcg)', app.db.Float)
    thiamine = app.db.Column('Tiamina (mg)', app.db.Float)
    riboflavin = app.db.Column('Riboflavina (mg)', app.db.Float)
    pyridoxine = app.db.Column('Piridoxina (mg)', app.db.Float)
    niacin = app.db.Column('Niacina (mg)', app.db.Float)
    vitamin_c = app.db.Column('Vitamina C (mg)', app.db.Float)


class Dairy(app.db.Model):
    __tablename__ = 'leite_e_derivados'

    id = app.db.Column('index', app.db.Integer, primary_key=True)
    description = app.db.Column('Descrição', app.db.String)
    humidity = app.db.Column('Umidade (%)', app.db.Float)
    energy_kcal = app.db.Column('Energia (kcal)', app.db.Integer)
    energy_kj = app.db.Column('Energia (kJ)', app.db.Integer)
    protein = app.db.Column('Proteína (g)', app.db.Float)
    fat = app.db.Column('Lipídeos (g)', app.db.Float)
    cholesterol = app.db.Column('Colesterol (mg)', app.db.Float)
    carbs = app.db.Column('Carboidrato (g)', app.db.Float)
    fiber = app.db.Column('Fibra Alimentar (g)', app.db.Float)
    calcium = app.db.Column('Cálcio (mg)', app.db.Float)
    magnesium = app.db.Column('Magnésio (mg)', app.db.Float)
    manganese = app.db.Column('Manganés (mg)', app.db.Float)
    phosphorus = app.db.Column('Fósforo (mg)', app.db.Float)
    iron = app.db.Column('Ferro (mg)', app.db.Float)
    sodium = app.db.Column('Sódio (mg)', app.db.Float)
    potassium = app.db.Column('Potássio (mg)', app.db.Float)
    copper = app.db.Column('Cobre (mg)', app.db.Float)
    zinc = app.db.Column('Zinco (mg)', app.db.Float)
    retinol = app.db.Column('Retinol (mcg)', app.db.Float)
    thiamine = app.db.Column('Tiamina (mg)', app.db.Float)
    riboflavin = app.db.Column('Riboflavina (mg)', app.db.Float)
    pyridoxine = app.db.Column('Piridoxina (mg)', app.db.Float)
    niacin = app.db.Column('Niacina (mg)', app.db.Float)
    vitamin_c = app.db.Column('Vitamina C (mg)', app.db.Float)


class Drinks(app.db.Model):
    __tablename__ = 'bebidas'

    id = app.db.Column('index', app.db.Integer, primary_key=True)
    description = app.db.Column('Descrição', app.db.String)
    humidity = app.db.Column('Umidade (%)', app.db.Float)
    energy_kcal = app.db.Column('Energia (kcal)', app.db.Integer)
    energy_kj = app.db.Column('Energia (kJ)', app.db.Integer)
    protein = app.db.Column('Proteína (g)', app.db.Float)
    fat = app.db.Column('Lipídeos (g)', app.db.Float)
    cholesterol = app.db.Column('Colesterol (mg)', app.db.Float)
    carbs = app.db.Column('Carboidrato (g)', app.db.Float)
    fiber = app.db.Column('Fibra Alimentar (g)', app.db.Float)
    calcium = app.db.Column('Cálcio (mg)', app.db.Float)
    magnesium = app.db.Column('Magnésio (mg)', app.db.Float)
    manganese = app.db.Column('Manganés (mg)', app.db.Float)
    phosphorus = app.db.Column('Fósforo (mg)', app.db.Float)
    iron = app.db.Column('Ferro (mg)', app.db.Float)
    sodium = app.db.Column('Sódio (mg)', app.db.Float)
    potassium = app.db.Column('Potássio (mg)', app.db.Float)
    copper = app.db.Column('Cobre (mg)', app.db.Float)
    zinc = app.db.Column('Zinco (mg)', app.db.Float)
    retinol = app.db.Column('Retinol (mcg)', app.db.Float)
    thiamine = app.db.Column('Tiamina (mg)', app.db.Float)
    riboflavin = app.db.Column('Riboflavina (mg)', app.db.Float)
    pyridoxine = app.db.Column('Piridoxina (mg)', app.db.Float)
    niacin = app.db.Column('Niacina (mg)', app.db.Float)
    vitamin_c = app.db.Column('Vitamina C (mg)', app.db.Float)


class Eggs(app.db.Model):
    __tablename__ = 'ovos_e_derivados'

    id = app.db.Column('index', app.db.Integer, primary_key=True)
    description = app.db.Column('Descrição', app.db.String)
    humidity = app.db.Column('Umidade (%)', app.db.Float)
    energy_kcal = app.db.Column('Energia (kcal)', app.db.Integer)
    energy_kj = app.db.Column('Energia (kJ)', app.db.Integer)
    protein = app.db.Column('Proteína (g)', app.db.Float)
    fat = app.db.Column('Lipídeos (g)', app.db.Float)
    cholesterol = app.db.Column('Colesterol (mg)', app.db.Float)
    carbs = app.db.Column('Carboidrato (g)', app.db.Float)
    fiber = app.db.Column('Fibra Alimentar (g)', app.db.Float)
    calcium = app.db.Column('Cálcio (mg)', app.db.Float)
    magnesium = app.db.Column('Magnésio (mg)', app.db.Float)
    manganese = app.db.Column('Manganés (mg)', app.db.Float)
    phosphorus = app.db.Column('Fósforo (mg)', app.db.Float)
    iron = app.db.Column('Ferro (mg)', app.db.Float)
    sodium = app.db.Column('Sódio (mg)', app.db.Float)
    potassium = app.db.Column('Potássio (mg)', app.db.Float)
    copper = app.db.Column('Cobre (mg)', app.db.Float)
    zinc = app.db.Column('Zinco (mg)', app.db.Float)
    retinol = app.db.Column('Retinol (mcg)', app.db.Float)
    thiamine = app.db.Column('Tiamina (mg)', app.db.Float)
    riboflavin = app.db.Column('Riboflavina (mg)', app.db.Float)
    pyridoxine = app.db.Column('Piridoxina (mg)', app.db.Float)
    niacin = app.db.Column('Niacina (mg)', app.db.Float)
    vitamin_c = app.db.Column('Vitamina C (mg)', app.db.Float)


class Sugar(app.db.Model):
    __tablename__ = 'produtos_acucarados'

    id = app.db.Column('index', app.db.Integer, primary_key=True)
    description = app.db.Column('Descrição', app.db.String)
    humidity = app.db.Column('Umidade (%)', app.db.Float)
    energy_kcal = app.db.Column('Energia (kcal)', app.db.Integer)
    energy_kj = app.db.Column('Energia (kJ)', app.db.Integer)
    protein = app.db.Column('Proteína (g)', app.db.Float)
    fat = app.db.Column('Lipídeos (g)', app.db.Float)
    cholesterol = app.db.Column('Colesterol (mg)', app.db.Float)
    carbs = app.db.Column('Carboidrato (g)', app.db.Float)
    fiber = app.db.Column('Fibra Alimentar (g)', app.db.Float)
    calcium = app.db.Column('Cálcio (mg)', app.db.Float)
    magnesium = app.db.Column('Magnésio (mg)', app.db.Float)
    manganese = app.db.Column('Manganés (mg)', app.db.Float)
    phosphorus = app.db.Column('Fósforo (mg)', app.db.Float)
    iron = app.db.Column('Ferro (mg)', app.db.Float)
    sodium = app.db.Column('Sódio (mg)', app.db.Float)
    potassium = app.db.Column('Potássio (mg)', app.db.Float)
    copper = app.db.Column('Cobre (mg)', app.db.Float)
    zinc = app.db.Column('Zinco (mg)', app.db.Float)
    retinol = app.db.Column('Retinol (mcg)', app.db.Float)
    thiamine = app.db.Column('Tiamina (mg)', app.db.Float)
    riboflavin = app.db.Column('Riboflavina (mg)', app.db.Float)
    pyridoxine = app.db.Column('Piridoxina (mg)', app.db.Float)
    niacin = app.db.Column('Niacina (mg)', app.db.Float)
    vitamin_c = app.db.Column('Vitamina C (mg)', app.db.Float)


class Miscellaneous(app.db.Model):
    __tablename__ = 'miscelaneas'

    id = app.db.Column('index', app.db.Integer, primary_key=True)
    description = app.db.Column('Descrição', app.db.String)
    humidity = app.db.Column('Umidade (%)', app.db.Float)
    energy_kcal = app.db.Column('Energia (kcal)', app.db.Integer)
    energy_kj = app.db.Column('Energia (kJ)', app.db.Integer)
    protein = app.db.Column('Proteína (g)', app.db.Float)
    fat = app.db.Column('Lipídeos (g)', app.db.Float)
    cholesterol = app.db.Column('Colesterol (mg)', app.db.Float)
    carbs = app.db.Column('Carboidrato (g)', app.db.Float)
    fiber = app.db.Column('Fibra Alimentar (g)', app.db.Float)
    calcium = app.db.Column('Cálcio (mg)', app.db.Float)
    magnesium = app.db.Column('Magnésio (mg)', app.db.Float)
    manganese = app.db.Column('Manganés (mg)', app.db.Float)
    phosphorus = app.db.Column('Fósforo (mg)', app.db.Float)
    iron = app.db.Column('Ferro (mg)', app.db.Float)
    sodium = app.db.Column('Sódio (mg)', app.db.Float)
    potassium = app.db.Column('Potássio (mg)', app.db.Float)
    copper = app.db.Column('Cobre (mg)', app.db.Float)
    zinc = app.db.Column('Zinco (mg)', app.db.Float)
    retinol = app.db.Column('Retinol (mcg)', app.db.Float)
    thiamine = app.db.Column('Tiamina (mg)', app.db.Float)
    riboflavin = app.db.Column('Riboflavina (mg)', app.db.Float)
    pyridoxine = app.db.Column('Piridoxina (mg)', app.db.Float)
    niacin = app.db.Column('Niacina (mg)', app.db.Float)
    vitamin_c = app.db.Column('Vitamina C (mg)', app.db.Float)


class Industrialized(app.db.Model):
    __tablename__ = 'outros_alimentos_industrializados'

    id = app.db.Column('index', app.db.Integer, primary_key=True)
    description = app.db.Column('Descrição', app.db.String)
    humidity = app.db.Column('Umidade (%)', app.db.Float)
    energy_kcal = app.db.Column('Energia (kcal)', app.db.Integer)
    energy_kj = app.db.Column('Energia (kJ)', app.db.Integer)
    protein = app.db.Column('Proteína (g)', app.db.Float)
    fat = app.db.Column('Lipídeos (g)', app.db.Float)
    cholesterol = app.db.Column('Colesterol (mg)', app.db.Float)
    carbs = app.db.Column('Carboidrato (g)', app.db.Float)
    fiber = app.db.Column('Fibra Alimentar (g)', app.db.Float)
    calcium = app.db.Column('Cálcio (mg)', app.db.Float)
    magnesium = app.db.Column('Magnésio (mg)', app.db.Float)
    manganese = app.db.Column('Manganés (mg)', app.db.Float)
    phosphorus = app.db.Column('Fósforo (mg)', app.db.Float)
    iron = app.db.Column('Ferro (mg)', app.db.Float)
    sodium = app.db.Column('Sódio (mg)', app.db.Float)
    potassium = app.db.Column('Potássio (mg)', app.db.Float)
    copper = app.db.Column('Cobre (mg)', app.db.Float)
    zinc = app.db.Column('Zinco (mg)', app.db.Float)
    retinol = app.db.Column('Retinol (mcg)', app.db.Float)
    thiamine = app.db.Column('Tiamina (mg)', app.db.Float)
    riboflavin = app.db.Column('Riboflavina (mg)', app.db.Float)
    pyridoxine = app.db.Column('Piridoxina (mg)', app.db.Float)
    niacin = app.db.Column('Niacina (mg)', app.db.Float)
    vitamin_c = app.db.Column('Vitamina C (mg)', app.db.Float)


class Prepared(app.db.Model):
    __tablename__ = 'alimentos_preparados'

    id = app.db.Column('index', app.db.Integer, primary_key=True)
    description = app.db.Column('Descrição', app.db.String)
    humidity = app.db.Column('Umidade (%)', app.db.Float)
    energy_kcal = app.db.Column('Energia (kcal)', app.db.Integer)
    energy_kj = app.db.Column('Energia (kJ)', app.db.Integer)
    protein = app.db.Column('Proteína (g)', app.db.Float)
    fat = app.db.Column('Lipídeos (g)', app.db.Float)
    cholesterol = app.db.Column('Colesterol (mg)', app.db.Float)
    carbs = app.db.Column('Carboidrato (g)', app.db.Float)
    fiber = app.db.Column('Fibra Alimentar (g)', app.db.Float)
    calcium = app.db.Column('Cálcio (mg)', app.db.Float)
    magnesium = app.db.Column('Magnésio (mg)', app.db.Float)
    manganese = app.db.Column('Manganés (mg)', app.db.Float)
    phosphorus = app.db.Column('Fósforo (mg)', app.db.Float)
    iron = app.db.Column('Ferro (mg)', app.db.Float)
    sodium = app.db.Column('Sódio (mg)', app.db.Float)
    potassium = app.db.Column('Potássio (mg)', app.db.Float)
    copper = app.db.Column('Cobre (mg)', app.db.Float)
    zinc = app.db.Column('Zinco (mg)', app.db.Float)
    retinol = app.db.Column('Retinol (mcg)', app.db.Float)
    thiamine = app.db.Column('Tiamina (mg)', app.db.Float)
    riboflavin = app.db.Column('Riboflavina (mg)', app.db.Float)
    pyridoxine = app.db.Column('Piridoxina (mg)', app.db.Float)
    niacin = app.db.Column('Niacina (mg)', app.db.Float)
    vitamin_c = app.db.Column('Vitamina C (mg)', app.db.Float)


class Legumes(app.db.Model):
    __tablename__ = 'leguminosas_e_derivados'

    id = app.db.Column('index', app.db.Integer, primary_key=True)
    description = app.db.Column('Descrição', app.db.String)
    humidity = app.db.Column('Umidade (%)', app.db.Float)
    energy_kcal = app.db.Column('Energia (kcal)', app.db.Integer)
    energy_kj = app.db.Column('Energia (kJ)', app.db.Integer)
    protein = app.db.Column('Proteína (g)', app.db.Float)
    fat = app.db.Column('Lipídeos (g)', app.db.Float)
    cholesterol = app.db.Column('Colesterol (mg)', app.db.Float)
    carbs = app.db.Column('Carboidrato (g)', app.db.Float)
    fiber = app.db.Column('Fibra Alimentar (g)', app.db.Float)
    calcium = app.db.Column('Cálcio (mg)', app.db.Float)
    magnesium = app.db.Column('Magnésio (mg)', app.db.Float)
    manganese = app.db.Column('Manganés (mg)', app.db.Float)
    phosphorus = app.db.Column('Fósforo (mg)', app.db.Float)
    iron = app.db.Column('Ferro (mg)', app.db.Float)
    sodium = app.db.Column('Sódio (mg)', app.db.Float)
    potassium = app.db.Column('Potássio (mg)', app.db.Float)
    copper = app.db.Column('Cobre (mg)', app.db.Float)
    zinc = app.db.Column('Zinco (mg)', app.db.Float)
    retinol = app.db.Column('Retinol (mcg)', app.db.Float)
    thiamine = app.db.Column('Tiamina (mg)', app.db.Float)
    riboflavin = app.db.Column('Riboflavina (mg)', app.db.Float)
    pyridoxine = app.db.Column('Piridoxina (mg)', app.db.Float)
    niacin = app.db.Column('Niacina (mg)', app.db.Float)
    vitamin_c = app.db.Column('Vitamina C (mg)', app.db.Float)


class NutsAndSeeds(app.db.Model):
    __tablename__ = 'nozes_e_sementes'

    id = app.db.Column('index', app.db.Integer, primary_key=True)
    description = app.db.Column('Descrição', app.db.String)
    humidity = app.db.Column('Umidade (%)', app.db.Float)
    energy_kcal = app.db.Column('Energia (kcal)', app.db.Integer)
    energy_kj = app.db.Column('Energia (kJ)', app.db.Integer)
    protein = app.db.Column('Proteína (g)', app.db.Float)
    fat = app.db.Column('Lipídeos (g)', app.db.Float)
    cholesterol = app.db.Column('Colesterol (mg)', app.db.Float)
    carbs = app.db.Column('Carboidrato (g)', app.db.Float)
    fiber = app.db.Column('Fibra Alimentar (g)', app.db.Float)
    calcium = app.db.Column('Cálcio (mg)', app.db.Float)
    magnesium = app.db.Column('Magnésio (mg)', app.db.Float)
    manganese = app.db.Column('Manganés (mg)', app.db.Float)
    phosphorus = app.db.Column('Fósforo (mg)', app.db.Float)
    iron = app.db.Column('Ferro (mg)', app.db.Float)
    sodium = app.db.Column('Sódio (mg)', app.db.Float)
    potassium = app.db.Column('Potássio (mg)', app.db.Float)
    copper = app.db.Column('Cobre (mg)', app.db.Float)
    zinc = app.db.Column('Zinco (mg)', app.db.Float)
    retinol = app.db.Column('Retinol (mcg)', app.db.Float)
    thiamine = app.db.Column('Tiamina (mg)', app.db.Float)
    riboflavin = app.db.Column('Riboflavina (mg)', app.db.Float)
    pyridoxine = app.db.Column('Piridoxina (mg)', app.db.Float)
    niacin = app.db.Column('Niacina (mg)', app.db.Float)
    vitamin_c = app.db.Column('Vitamina C (mg)', app.db.Float)
